services:
  - type: web
    name: standby-scheduler
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: TZ
        value: Asia/Jakarta
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_SECURE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_SUBJECT_H1
        sync: false
      - key: EMAIL_SUBJECT_H
        sync: false
      - key: EMAIL_DIRGA
        sync: false
      - key: EMAIL_HILMI
        sync: false
      - key: EMAIL_ARDAN
        sync: false
      - key: EMAIL_ALAWI
        sync: false
      - key: EMAIL_FARHAN
        sync: false
      - key: EMAIL_RHEZA
        sync: false
      - key: EMAIL_VIGO
        sync: false
      - key: EMAIL_RINE
        sync: false
      - key: EMAIL_IRA
        sync: false
      - key: EMAIL_MIFTAH
        sync: false
      - key: EMAIL_MAULANA
        sync: false
      - key: EMAIL_CHABIB
        sync: false
      - key: EMAIL_NEZA
        sync: false
